## USERS
### GET ALL USERS
GET http://localhost:8080/api/users HTTP/1.1
Content-Type: application/json

### GET USER BY ID
GET http://localhost:8080/api/users/1 HTTP/1.1
Content-Type: application/json

### CREATE ONE USER
POST https://economic-blog-backend.up.railway.app/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "username": "alex",
    "email": "alex@email.com",
    "password": "contraseña"
}

### LOGIN USER
POST http://localhost:8080/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "bujosa2023@gmail.com",
    "password": "Bujosa20232"
}

## ARTICLES
### GET ALL ARTICLES
GET http://localhost:8080/api/articles HTTP/1.1
Content-Type: application/json

### GET ARTICLES BY CATEGORY
GET http://localhost:8080/api/articles/category/Global HTTP/1.1
Content-Type: application/json

### GET ARTICLE BY ID
GET http://localhost:8080/api/articles/1 HTTP/1.1
Content-Type: application/json

### CREATE ONE ARTICLE
POST http://localhost:8080/api/articles HTTP/1.1
Content-Type: application/json

{
    "": ,
}

### UPDATE ONE ARTICLE BY ID
PATCH  http://localhost:8080/api/articles/1 HTTP/1.1
Content-Type: application/json

{
    "": ,
}

### DELETE ONE ARTICLE BY ID
DELETE http://localhost:8080/api/articles/1 HTTP/1.1
Content-Type: application/json

{
    "": ,
}

## USERS
### CREATE ONE COMMENT
POST http://localhost:8080/api/comments HTTP/1.1
Content-Type: application/json

{
    "article": "63ae70d69b0d644655b8703f",
    "user": "63ae831e6c89f24f17b5a674", 
    "body": "Probando"
}